=== EmadAhmedNasef/Attendance-Management-System/XML/autontication.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="authentication">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="username" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="role">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Admin"/>
                                        <xs:enumeration value="Teacher"/>
                                        <xs:enumeration value="Student"/>
                                        <!-- Additional roles can be added here -->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== EmadAhmedNasef/Attendance-Management-System/XML/authontication.xml
<authentication xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\Study\Courses\Fullstack\ITI C44\C# [Programming]\Attendance-Management-System-abdellatief\XML\autontication.xsd">
	<user>
		<username>admin</username>
		<password>admin123</password>
		<role>Admin</role>
	</user>
	<user>
		<username>teacher1</username>
		<password>teacher123</password>
		<role>Teacher</role>
	</user>
	<user>
		<username>student1</username>
		<password>student123</password>
		<role>Student</role>
	</user>
	<!-- Additional users and roles can be added here -->
</authentication>
