=== EmadAhmedNasef/Attendance-Management-System/XML/Records.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="records">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="record" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="date" type="xs:date"/>
							<xs:element name="class" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Teacher">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="teacherName" type="xs:string"/>
													<xs:element name="teacherID" type="xs:int"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Students">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Student" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="studentname" type="xs:string"/>
																<xs:element name="studentID" type="xs:int"/>
																<xs:element name="status" type="xs:string"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EmadAhmedNasef/Attendance-Management-System/XML/record2.xml
<records xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Nasef\Desktop\Project\XML\Records.xsd">
  <record>
    <date>2023-12-05</date>
    <class name="Math">
      <Teacher>
        <teacherName>hamed</teacherName>
        <teacherID>2</teacherID>
      </Teacher>
      <Students>
        <Student>
          <studentname>sayed</studentname>
          <studentID>4</studentID>
          <status>Absent</status>
        </Student>
        <Student>
          <studentname>mohamed </studentname>
          <studentID>3</studentID>
          <status>Absent</status>
        </Student>
      </Students>
    </class>
    <class name="English">
      <Teacher>
        <teacherName>Ahmed</teacherName>
        <teacherID>6</teacherID>
      </Teacher>
      <Students>
        <Student>
          <studentname>sayed</studentname>
          <studentID>4</studentID>
          <status>Absent</status>
        </Student>
        <Student>
          <studentname>mohamed </studentname>
          <studentID>3</studentID>
          <status>Absent</status>
        </Student>
      </Students>
    </class>
    <class name="Math">
      <Teacher>
        <teacherName>hamed</teacherName>
        <teacherID>2</teacherID>
      </Teacher>
      <Students>
        <Student>
          <studentname>abdellatief hamed</studentname>
          <studentID>5</studentID>
          <status>Absent</status>
        </Student>
      </Students>
    </class>
    <class name="English">
      <Teacher>
        <teacherName>Ahmed</teacherName>
        <teacherID>6</teacherID>
      </Teacher>
      <Students>
        <Student>
          <studentname>abdellatief hamed</studentname>
          <studentID>5</studentID>
          <status>Absent</status>
        </Student>
      </Students>
    </class>
  </record>
  <record>
    <date>2023-11-05</date>
    <class name="Math">
      <Teacher>
        <teacherName>hamed</teacherName>
        <teacherID>2</teacherID>
      </Teacher>
      <Students>
        <Student>
          <studentname>sayed</studentname>
          <studentID>4</studentID>
          <status>Present</status>
        </Student>
        <Student>
          <studentname>mohamed </studentname>
          <studentID>3</studentID>
          <status>Present</status>
        </Student>
      </Students>
    </class>
    <class name="English">
      <Teacher>
        <teacherName>Ahmed</teacherName>
        <teacherID>6</teacherID>
      </Teacher>
      <Students>
        <Student>
          <studentname>sayed</studentname>
          <studentID>4</studentID>
          <status>Present</status>
        </Student>
        <Student>
          <studentname>mohamed </studentname>
          <studentID>3</studentID>
          <status>Present</status>
        </Student>
      </Students>
    </class>
    <class name="Math">
      <Teacher>
        <teacherName>hamed</teacherName>
        <teacherID>2</teacherID>
      </Teacher>
      <Students>
        <Student>
          <studentname>abdellatief hamed</studentname>
          <studentID>5</studentID>
          <status>Present</status>
        </Student>
      </Students>
    </class>
    <class name="English">
      <Teacher>
        <teacherName>Ahmed</teacherName>
        <teacherID>6</teacherID>
      </Teacher>
      <Students>
        <Student>
          <studentname>abdellatief hamed</studentname>
          <studentID>5</studentID>
          <status>Present</status>
        </Student>
      </Students>
    </class>
  </record>
</records>
